# DATA CLEAN USING PANDAS

1. Loading a raw dataset
2. Detecting and removing duplicates
3. Detecting missing values
4. Cleaning the name column
5. Removing missing values (age column)
6. Cleaning categorical data (gender, grade columns) 
7. Dealing with Score columns (both numeric and categorical)
8. Dealing with Dates
9. Cleaning again categorical data
10. Outro

1. Import libraries and Loading a raw dataset

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r"D:\Datamites\Data_Clean\students_data.csv")
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     31 non-null     int64
 1   name           31 non-null     str
 2   age            28 non-null     float64
 3   gender         31 non-null     str
 4   grade          31 non-null     str
 5   math_score     13 non-null     float64
 6   english_score  23 non-null     str
 7   science_score  31 non-null     int64
 8   enrolled_date  31 non-null     str
 9   remarks        31 non-null     str
dtypes: float64(2), int64(2), str(6)
memory usage: 3.7 KB

2. Detecting and removing duplicates

In [9]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
dtype: bool

In [10]:
# drop dupplicate data

df.drop_duplicates()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [12]:
df
# its not affected to original datafram that's why you need to aasign it to original dataframe

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [15]:
df = df.drop_duplicates()
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,jane smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,jane smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,lucy gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,jane smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

3. Detecting missing values

In [17]:
df.isnull()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,True,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,True,True,False,False,False
6,False,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,True,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,True,False,False,False,False
12,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,True,True,False,False,False
14,False,False,False,False,False,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,True,False,False,True,True,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,True,False,False,False
20,False,False,False,False,False,True,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,True,False,False,False
23,False,False,False,False,False,True,False,False,False,False
24,False,False,False,False,False,True,True,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,True,False,False,False,False,False,False,False
27,False,False,False,False,False,True,False,False,False,False
28,False,False,False,False,False,True,False,False,False,False
29,False,False,False,False,False,True,False,False,False,False

In [18]:
df.isnull().sum()

student_id        0
name              0
age               3
gender            0
grade             0
math_score       17
english_score     8
science_score     0
enrolled_date     0
remarks           0
dtype: int64

4. Cleaning the name column

In [19]:
df['name']

0        jane smith
1          John Doe
2          Chris P.
3        jane smith
4       Sara O'Neil
5     Mike O’Reilly
6          ali Khan
7       Sara O'Neil
8     Mike O’Reilly
9      Robert Brown
10        lucy gray
11     Simran Singh
12         Patel R.
13         Patel R.
14         Ali Khan
15        Lucy gray
16         Chris P.
17         Ali Khan
18     Simran Singh
19         Patel R.
20      Sara O'Neil
21         John Doe
22      Sara O'Neil
23       jane smith
24         John Doe
25    Mike O’Reilly
26         John Doe
27     Simran Singh
28      Sara O'Neil
29         Patel R.
Name: name, dtype: str

In [21]:
# The first letter we have to make CAPITAL
# first make it as string 'str' the lower the all letter's
df['name'].str.lower()

0        jane smith
1          john doe
2          chris p.
3        jane smith
4       sara o'neil
5     mike o’reilly
6          ali khan
7       sara o'neil
8     mike o’reilly
9      robert brown
10        lucy gray
11     simran singh
12         patel r.
13         patel r.
14         ali khan
15        lucy gray
16         chris p.
17         ali khan
18     simran singh
19         patel r.
20      sara o'neil
21         john doe
22      sara o'neil
23       jane smith
24         john doe
25    mike o’reilly
26         john doe
27     simran singh
28      sara o'neil
29         patel r.
Name: name, dtype: str

In [23]:
# make again 'str' then make title() case 
# title() case make the first letter of each word as a CAPITAL
df['name'].str.lower().str.title()

0        Jane Smith
1          John Doe
2          Chris P.
3        Jane Smith
4       Sara O'Neil
5     Mike O’Reilly
6          Ali Khan
7       Sara O'Neil
8     Mike O’Reilly
9      Robert Brown
10        Lucy Gray
11     Simran Singh
12         Patel R.
13         Patel R.
14         Ali Khan
15        Lucy Gray
16         Chris P.
17         Ali Khan
18     Simran Singh
19         Patel R.
20      Sara O'Neil
21         John Doe
22      Sara O'Neil
23       Jane Smith
24         John Doe
25    Mike O’Reilly
26         John Doe
27     Simran Singh
28      Sara O'Neil
29         Patel R.
Name: name, dtype: str

In [26]:
# Assign the above solution to your original dataframe by using label indexing loc[]
df.loc[:,'name'] = df['name'].str.lower().str.title()

In [27]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

5. Removing missing values (age column)

In [29]:
df['age']

0     16.0
1     16.0
2      NaN
3     16.0
4     16.0
5     16.0
6     17.0
7     17.0
8     16.0
9     17.0
10    17.0
11    16.0
12    17.0
13    17.0
14    17.0
15    16.0
16     NaN
17    18.0
18    17.0
19    17.0
20    17.0
21    18.0
22    17.0
23    17.0
24    18.0
25    17.0
26     NaN
27    16.0
28    17.0
29    17.0
Name: age, dtype: float64

In [33]:
# Dealing with null values
# Check unique values first
df['age'].unique()

array([16., nan, 17., 18.])

In [34]:
# fill the null values with mean() or median() or you cannot always fill the null values
# with mean() or median it depends on your dataset column values
df['age'].mean()

np.float64(16.77777777777778)

In [38]:
# dont fill with floating values you should it with '0'by using using round()
age_mean = df['age'].mean().round()

In [39]:
age_mean

np.float64(17.0)

In [40]:
# fill the above mean values to null values using fillna()
df['age'].fillna(age_mean)

0     16.0
1     16.0
2     17.0
3     16.0
4     16.0
5     16.0
6     17.0
7     17.0
8     16.0
9     17.0
10    17.0
11    16.0
12    17.0
13    17.0
14    17.0
15    16.0
16    17.0
17    18.0
18    17.0
19    17.0
20    17.0
21    18.0
22    17.0
23    17.0
24    18.0
25    17.0
26    17.0
27    16.0
28    17.0
29    17.0
Name: age, dtype: float64

In [43]:
# assign it to your original dafaframe
df.loc[:,'age'] = df['age'].fillna(age_mean)

In [44]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [45]:
# agian check the missing values
df.isnull().sum()

student_id        0
name              0
age               0
gender            0
grade             0
math_score       17
english_score     8
science_score     0
enrolled_date     0
remarks           0
dtype: int64

6. Cleaning categorical data (gender, grade columns)

In [46]:
df['gender']

0     female
1       Male
2       MALE
3     FEMALE
4       male
5     Female
6     female
7     female
8     Female
9     female
10      male
11    FEMALE
12    female
13      male
14      male
15    Female
16    Female
17      male
18      Male
19      MALE
20      Male
21    female
22      MALE
23    Female
24      MALE
25      Male
26      Male
27    FEMALE
28    female
29      male
Name: gender, dtype: str

In [47]:
# check the unique values in the gender column
df['gender'].unique()

<ArrowStringArray>
['female', 'Male', 'MALE', 'FEMALE', 'male', 'Female']
Length: 6, dtype: str

In [48]:
# Convert the above gender column values into a single formate 
# The first letter we have to make CAPITAL
# first make it as string 'str' the lower the all letter's

In [50]:
df['gender'].str.lower()

0     female
1       male
2       male
3     female
4       male
5     female
6     female
7     female
8     female
9     female
10      male
11    female
12    female
13      male
14      male
15    female
16    female
17      male
18      male
19      male
20      male
21    female
22      male
23    female
24      male
25      male
26      male
27    female
28    female
29      male
Name: gender, dtype: str

In [56]:
# make again or convert int into 'str' then make title() case 
# title() case make the first letter of each word as a CAPITAL
df['gender'].str.lower().str.title()

0     Female
1       Male
2       Male
3     Female
4       Male
5     Female
6     Female
7     Female
8     Female
9     Female
10      Male
11    Female
12    Female
13      Male
14      Male
15    Female
16    Female
17      Male
18      Male
19      Male
20      Male
21    Female
22      Male
23    Female
24      Male
25      Male
26      Male
27    Female
28    Female
29      Male
Name: gender, dtype: str

In [53]:
df.loc[:,'gender'] = df['gender'].str.lower().str.title()

In [54]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,Female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,Female,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,Male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,Female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,Female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,Male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,Female,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,Female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,Male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,Male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,Male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,Male,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,Female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,Male,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,Male,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,Female,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,Female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,Male,11,NaN,64,83,2022/06/11,Average

In [55]:
df['gender'].unique()

<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

In [58]:
# go with grade column
df.columns

Index(['student_id', 'name', 'age', 'gender', 'grade', 'math_score',
       'english_score', 'science_score', 'enrolled_date', 'remarks'],
      dtype='str')

In [59]:
df['grade']

0       11
1     10th
2       10
3       10
4       11
5       10
6       11
7       12
8       12
9       12
10    11th
11    11th
12      11
13      10
14      12
15      12
16      11
17    11th
18      10
19    11th
20      10
21      11
22    11th
23    11th
24    11th
25      12
26    10th
27      12
28      11
29      11
Name: grade, dtype: str

In [60]:
# Check the unique values
df['grade'].unique()

<ArrowStringArray>
['11', '10th', '10', '12', '11th']
Length: 5, dtype: str

In [64]:
# replace 10th with 10 and 11th with 11
df['grade'].replace({"10th":"10","11th":"11"})

0     11
1     10
2     10
3     10
4     11
5     10
6     11
7     12
8     12
9     12
10    11
11    11
12    11
13    10
14    12
15    12
16    11
17    11
18    10
19    11
20    10
21    11
22    11
23    11
24    11
25    12
26    10
27    12
28    11
29    11
Name: grade, dtype: str

In [66]:
df.loc[:,'grade'] = df['grade'].replace({"10th":"10","11th":"11"})

In [67]:
df['grade'].unique()

<ArrowStringArray>
['11', '10', '12']
Length: 3, dtype: str

In [68]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,Female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,17.0,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,Female,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,Male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,Female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,Female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,Male,11,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,Female,11,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,Female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,Male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,Male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,17.0,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,Male,11,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,Male,11,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,Female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,Male,11,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,Male,11,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,17.0,Male,10,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,Female,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,Female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,Male,11,NaN,64,83,2022/06/11,Average

7. Dealing with Score columns (both numeric and categorical)

In [73]:
df['math_score']

0      75.0
1      74.0
2       NaN
3       NaN
4       NaN
5       NaN
6      64.0
7       NaN
8      80.0
9       NaN
10     65.0
11      NaN
12      NaN
13      NaN
14      NaN
15     65.0
16      NaN
17     67.0
18    100.0
19     73.0
20      NaN
21     66.0
22     75.0
23      NaN
24      NaN
25     94.0
26     64.0
27      NaN
28      NaN
29      NaN
Name: math_score, dtype: float64

In [77]:
# The above column is float datatype and there is no decimal value at that time we will use mean() values
# lets check the mean() value in this column first
mean_math_score = df['math_score'].mean()
mean_math_score

np.float64(74.0)

In [80]:
# the above mean value is good because there is no decimal values and we can fill it into the null or missing values by using fillna()
df['math_score'].fillna(mean_math_score)

0      75.0
1      74.0
2      74.0
3      74.0
4      74.0
5      74.0
6      64.0
7      74.0
8      80.0
9      74.0
10     65.0
11     74.0
12     74.0
13     74.0
14     74.0
15     65.0
16     74.0
17     67.0
18    100.0
19     73.0
20     74.0
21     66.0
22     75.0
23     74.0
24     74.0
25     94.0
26     64.0
27     74.0
28     74.0
29     74.0
Name: math_score, dtype: float64

In [81]:
df.loc[:,'math_score'] = df['math_score'].fillna(mean_math_score)

In [82]:
df['math_score']

0      75.0
1      74.0
2      74.0
3      74.0
4      74.0
5      74.0
6      64.0
7      74.0
8      80.0
9      74.0
10     65.0
11     74.0
12     74.0
13     74.0
14     74.0
15     65.0
16     74.0
17     67.0
18    100.0
19     73.0
20     74.0
21     66.0
22     75.0
23     74.0
24     74.0
25     94.0
26     64.0
27     74.0
28     74.0
29     74.0
Name: math_score, dtype: float64

In [84]:
df.isnull()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,True,False,False,False
6,False,False,False,False,False,False,True,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,True,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,True,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,True,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,True,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,True,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False

In [85]:
df['english_score']

0         NaN
1          95
2     missing
3     missing
4          96
5         NaN
6         NaN
7          63
8     missing
9     missing
10         67
11    missing
12         87
13        NaN
14         91
15         91
16        NaN
17         74
18         74
19        NaN
20    missing
21         72
22        NaN
23    missing
24        NaN
25         80
26    missing
27         76
28         64
29         64
Name: english_score, dtype: str

In [86]:
df['english_score'].isnull()

0      True
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16     True
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24     True
25    False
26    False
27    False
28    False
29    False
Name: english_score, dtype: bool

In [90]:
df['english_score'].unique()

<ArrowStringArray>
[      nan,      '95', 'missing',      '96',      '63',      '67',      '87',
      '91',      '74',      '72',      '80',      '76',      '64']
Length: 13, dtype: str

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     30 non-null     int64
 1   name           30 non-null     str
 2   age            30 non-null     float64
 3   gender         30 non-null     str
 4   grade          30 non-null     str
 5   math_score     30 non-null     float64
 6   english_score  22 non-null     str
 7   science_score  30 non-null     int64
 8   enrolled_date  30 non-null     str
 9   remarks        30 non-null     str
dtypes: float64(2), int64(2), str(6)
memory usage: 3.6 KB

In [96]:
# Convert the string into the number using to_numeric() in pandas
pd.to_numeric(df['english_score'])

ValueError: Unable to parse string "missing" at position 2

In [100]:
# it will show error check what is the issue
# it will convert the string alphabet to 'n' not a number value lets check it
pd.to_numeric(df['english_score'],errors = 'coerce')
# you can see here where 'missing_value' is there . So missing where 'missing' string is there
# it converted into the 'nan'. So what we have to do we are going to deal with this and we are
# going to store this whole thing into our coordinal data frame.
# So. what we have to do we are going to use into our dataframe that is score.

0      NaN
1     95.0
2      NaN
3      NaN
4     96.0
5      NaN
6      NaN
7     63.0
8      NaN
9      NaN
10    67.0
11     NaN
12    87.0
13     NaN
14    91.0
15    91.0
16     NaN
17    74.0
18    74.0
19     NaN
20     NaN
21    72.0
22     NaN
23     NaN
24     NaN
25    80.0
26     NaN
27    76.0
28    64.0
29    64.0
Name: english_score, dtype: float64

In [105]:
# Then assign it into our original dataframe
df.loc[:,'english_score'] = pd.to_numeric(df['english_score'], errors = 'coerce')

In [108]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100.0,Jane Smith,16.0,Female,11,75.0,NaN,66.0,2022-06-10,excellent
1,101.0,John Doe,16.0,Male,10,74.0,95.0,94.0,10-06-2022,GOOD
2,102.0,Chris P.,17.0,Male,10,74.0,NaN,69.0,06/12/2022,needs improvement
3,103.0,Jane Smith,16.0,Female,10,74.0,NaN,62.0,10-06-2022,average
4,104.0,Sara O'Neil,16.0,Male,11,74.0,96.0,64.0,2022-06-10,GOOD
5,105.0,Mike O’Reilly,16.0,Female,10,74.0,NaN,83.0,06/12/2022,needs improvement
6,106.0,Ali Khan,17.0,Female,11,64.0,NaN,75.0,06/12/2022,Good
7,107.0,Sara O'Neil,17.0,Female,12,74.0,63.0,62.0,2022/06/11,excellent
8,108.0,Mike O’Reilly,16.0,Female,12,80.0,NaN,89.0,06/12/2022,poor
9,109.0,Robert Brown,17.0,Female,12,74.0,NaN,97.0,10-06-2022,needs improvement
10,110.0,Lucy Gray,17.0,Male,11,65.0,67.0,100.0,06/12/2022,excellent
11,111.0,Simran Singh,16.0,Female,11,74.0,NaN,95.0,2022-06-10,average
12,112.0,Patel R.,17.0,Female,11,74.0,87.0,89.0,2022-06-10,poor
13,113.0,Patel R.,17.0,Male,10,74.0,NaN,98.0,06/12/2022,Average
14,114.0,Ali Khan,17.0,Male,12,74.0,91.0,67.0,2022/06/11,poor
15,115.0,Lucy Gray,16.0,Female,12,65.0,91.0,94.0,06/12/2022,Average
16,116.0,Chris P.,17.0,Female,11,74.0,NaN,72.0,2022/06/11,excellent
17,117.0,Ali Khan,18.0,Male,11,67.0,74.0,81.0,2022-06-10,GOOD
18,118.0,Simran Singh,17.0,Male,10,100.0,74.0,62.0,2022/06/11,average
19,119.0,Patel R.,17.0,Male,11,73.0,NaN,90.0,06/12/2022,Good
20,120.0,Sara O'Neil,17.0,Male,10,74.0,NaN,89.0,2022-06-10,average
21,121.0,John Doe,18.0,Female,11,66.0,72.0,94.0,10-06-2022,Average
22,122.0,Sara O'Neil,17.0,Male,11,75.0,NaN,66.0,2022-06-10,good student
23,123.0,Jane Smith,17.0,Female,11,74.0,NaN,63.0,06/12/2022,excellent
24,124.0,John Doe,18.0,Male,11,74.0,NaN,91.0,06/12/2022,GOOD
25,125.0,Mike O’Reilly,17.0,Male,12,94.0,80.0,63.0,10-06-2022,Average
26,126.0,John Doe,17.0,Male,10,64.0,NaN,67.0,06/12/2022,good student
27,127.0,Simran Singh,16.0,Female,12,74.0,76.0,80.0,06/12/2022,poor
28,128.0,Sara O'Neil,17.0,Female,11,74.0,64.0,89.0,2022-06-10,average
29,129.0,Patel R.,17.0,Male,11,74.0,64.0,83.0,2022/06/11,Average
english_score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
# moe we are filling above 'english_column' value 'NAN' using 'mean()' or 'median()'
mean_english = df['english_score'].mean().round()
mean_english

np.float64(78.0)

In [114]:
df['english_score'].fillna(mean_english)

0                78.0
1                95.0
2                78.0
3                78.0
4                96.0
5                78.0
6                78.0
7                63.0
8                78.0
9                78.0
10               67.0
11               78.0
12               87.0
13               78.0
14               91.0
15               91.0
16               78.0
17               74.0
18               74.0
19               78.0
20               78.0
21               72.0
22               78.0
23               78.0
24               78.0
25               80.0
26               78.0
27               76.0
28               64.0
29               64.0
english_score    78.0
Name: english_score, dtype: object

In [116]:
# now again assign it into original data frame
df.loc[:,'english_score'] = df['english_score'].fillna(mean_english)
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100.0,Jane Smith,16.0,Female,11,75.0,78.0,66.0,2022-06-10,excellent
1,101.0,John Doe,16.0,Male,10,74.0,95.0,94.0,10-06-2022,GOOD
2,102.0,Chris P.,17.0,Male,10,74.0,78.0,69.0,06/12/2022,needs improvement
3,103.0,Jane Smith,16.0,Female,10,74.0,78.0,62.0,10-06-2022,average
4,104.0,Sara O'Neil,16.0,Male,11,74.0,96.0,64.0,2022-06-10,GOOD
5,105.0,Mike O’Reilly,16.0,Female,10,74.0,78.0,83.0,06/12/2022,needs improvement
6,106.0,Ali Khan,17.0,Female,11,64.0,78.0,75.0,06/12/2022,Good
7,107.0,Sara O'Neil,17.0,Female,12,74.0,63.0,62.0,2022/06/11,excellent
8,108.0,Mike O’Reilly,16.0,Female,12,80.0,78.0,89.0,06/12/2022,poor
9,109.0,Robert Brown,17.0,Female,12,74.0,78.0,97.0,10-06-2022,needs improvement
10,110.0,Lucy Gray,17.0,Male,11,65.0,67.0,100.0,06/12/2022,excellent
11,111.0,Simran Singh,16.0,Female,11,74.0,78.0,95.0,2022-06-10,average
12,112.0,Patel R.,17.0,Female,11,74.0,87.0,89.0,2022-06-10,poor
13,113.0,Patel R.,17.0,Male,10,74.0,78.0,98.0,06/12/2022,Average
14,114.0,Ali Khan,17.0,Male,12,74.0,91.0,67.0,2022/06/11,poor
15,115.0,Lucy Gray,16.0,Female,12,65.0,91.0,94.0,06/12/2022,Average
16,116.0,Chris P.,17.0,Female,11,74.0,78.0,72.0,2022/06/11,excellent
17,117.0,Ali Khan,18.0,Male,11,67.0,74.0,81.0,2022-06-10,GOOD
18,118.0,Simran Singh,17.0,Male,10,100.0,74.0,62.0,2022/06/11,average
19,119.0,Patel R.,17.0,Male,11,73.0,78.0,90.0,06/12/2022,Good
20,120.0,Sara O'Neil,17.0,Male,10,74.0,78.0,89.0,2022-06-10,average
21,121.0,John Doe,18.0,Female,11,66.0,72.0,94.0,10-06-2022,Average
22,122.0,Sara O'Neil,17.0,Male,11,75.0,78.0,66.0,2022-06-10,good student
23,123.0,Jane Smith,17.0,Female,11,74.0,78.0,63.0,06/12/2022,excellent
24,124.0,John Doe,18.0,Male,11,74.0,78.0,91.0,06/12/2022,GOOD
25,125.0,Mike O’Reilly,17.0,Male,12,94.0,80.0,63.0,10-06-2022,Average
26,126.0,John Doe,17.0,Male,10,64.0,78.0,67.0,06/12/2022,good student
27,127.0,Simran Singh,16.0,Female,12,74.0,76.0,80.0,06/12/2022,poor
28,128.0,Sara O'Neil,17.0,Female,11,74.0,64.0,89.0,2022-06-10,average
29,129.0,Patel R.,17.0,Male,11,74.0,64.0,83.0,2022/06/11,Average
english_score,NaN,NaN,NaN,NaN,NaN,NaN,78.0,NaN,NaN,NaN

8. Dealing with Dates

In [117]:
df['enrolled_date']

0                2022-06-10
1                10-06-2022
2                06/12/2022
3                10-06-2022
4                2022-06-10
5                06/12/2022
6                06/12/2022
7                2022/06/11
8                06/12/2022
9                10-06-2022
10               06/12/2022
11               2022-06-10
12               2022-06-10
13               06/12/2022
14               2022/06/11
15               06/12/2022
16               2022/06/11
17               2022-06-10
18               2022/06/11
19               06/12/2022
20               2022-06-10
21               10-06-2022
22               2022-06-10
23               06/12/2022
24               06/12/2022
25               10-06-2022
26               06/12/2022
27               06/12/2022
28               2022-06-10
29               2022/06/11
english_score           NaN
Name: enrolled_date, dtype: object

In [119]:
df['enrolled_date'].unique()

array(['2022-06-10', '10-06-2022', '06/12/2022', '2022/06/11', nan],
      dtype=object)

In [122]:
# Convert the date formate into proper formate i.e : '2022-06-10 (yyyy-month-day)
dict_date = {
    '10-06-2022':'2022-06-10',
    '06/12/2022':'2022-06-12',
    '2022/06/11':'2022-06-11'
}
dict_date

{'10-06-2022': '2022-06-10',
 '06/12/2022': '2022-06-12',
 '2022/06/11': '2022-06-11'}

In [123]:
df['enrolled_date'].replace(dict_date)

0                2022-06-10
1                2022-06-10
2                2022-06-12
3                2022-06-10
4                2022-06-10
5                2022-06-12
6                2022-06-12
7                2022-06-11
8                2022-06-12
9                2022-06-10
10               2022-06-12
11               2022-06-10
12               2022-06-10
13               2022-06-12
14               2022-06-11
15               2022-06-12
16               2022-06-11
17               2022-06-10
18               2022-06-11
19               2022-06-12
20               2022-06-10
21               2022-06-10
22               2022-06-10
23               2022-06-12
24               2022-06-12
25               2022-06-10
26               2022-06-12
27               2022-06-12
28               2022-06-10
29               2022-06-11
english_score           NaN
Name: enrolled_date, dtype: object

In [127]:
# Update into original dataframe
df.loc[:,'enrolled_date'] = df['enrolled_date'].replace(dict_date)

In [129]:
df['enrolled_date']

0                2022-06-10
1                2022-06-10
2                2022-06-12
3                2022-06-10
4                2022-06-10
5                2022-06-12
6                2022-06-12
7                2022-06-11
8                2022-06-12
9                2022-06-10
10               2022-06-12
11               2022-06-10
12               2022-06-10
13               2022-06-12
14               2022-06-11
15               2022-06-12
16               2022-06-11
17               2022-06-10
18               2022-06-11
19               2022-06-12
20               2022-06-10
21               2022-06-10
22               2022-06-10
23               2022-06-12
24               2022-06-12
25               2022-06-10
26               2022-06-12
27               2022-06-12
28               2022-06-10
29               2022-06-11
english_score           NaN
Name: enrolled_date, dtype: object

In [132]:
# One more important thing with dates is see the above dtype is object
# basically all are are string then what will you do
# we have to convert it into the date formate so what we can do 
# we have one function called 'pd.to_datetime()'
pd.to_datetime(df['enrolled_date'])
# check the datatype below

0               2022-06-10
1               2022-06-10
2               2022-06-12
3               2022-06-10
4               2022-06-10
5               2022-06-12
6               2022-06-12
7               2022-06-11
8               2022-06-12
9               2022-06-10
10              2022-06-12
11              2022-06-10
12              2022-06-10
13              2022-06-12
14              2022-06-11
15              2022-06-12
16              2022-06-11
17              2022-06-10
18              2022-06-11
19              2022-06-12
20              2022-06-10
21              2022-06-10
22              2022-06-10
23              2022-06-12
24              2022-06-12
25              2022-06-10
26              2022-06-12
27              2022-06-12
28              2022-06-10
29              2022-06-11
english_score          NaT
Name: enrolled_date, dtype: datetime64[us]

9. Cleaning again categorical data (remark column)

In [135]:
# one thing we can do basically
df['remarks'].unique()

array(['excellent', 'GOOD', 'needs improvement', 'average', 'Good',
       'poor', 'Average', 'good student', nan], dtype=object)

In [136]:
dict_remarks = {
    'excellent': 'Excellent',
    'GOOD': 'Good',
    'needs improvement': 'Needs Improvement',
    'average': 'Average',
    'poor': 'Poor',
    'good student': 'Good Student'
}

In [137]:
dict_remarks

{'excellent': 'Excellent',
 'GOOD': 'Good',
 'needs improvement': 'Needs Improvement',
 'average': 'Average',
 'poor': 'Poor',
 'good student': 'Good Student'}

In [138]:
df['remarks'].replace(dict_remarks).unique()

array(['Excellent', 'Good', 'Needs Improvement', 'Average', 'Poor',
       'Good Student', nan], dtype=object)

In [140]:
df.loc[:,'remarks'] = df['remarks'].replace(dict_remarks)

In [142]:
df['remarks']

0                        Excellent
1                             Good
2                Needs Improvement
3                          Average
4                             Good
5                Needs Improvement
6                             Good
7                        Excellent
8                             Poor
9                Needs Improvement
10                       Excellent
11                         Average
12                            Poor
13                         Average
14                            Poor
15                         Average
16                       Excellent
17                            Good
18                         Average
19                            Good
20                         Average
21                         Average
22                    Good Student
23                       Excellent
24                            Good
25                         Average
26                    Good Student
27                            Poor
28                         Average
29                         Average
english_score                  NaN
Name: remarks, dtype: object

In [143]:
pwd

'C:\\Users\\JAFFAR\\Home\\Machine Learning'