# Pandas

In [1]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# import pandas
import pandas as pd

In [3]:
# pnadas version
pd.__version__

'3.0.3'

  # Topics
  1. Create Dataframe
  2. Basic Dataframe Understanding
  3. Save and Load data from csv
  4. Rows and Columns - Selection
  5. Filter dataframe
  6. Rows and Columns - operation (Add,update,delete)
  7. Working with date value
  8. Handling missing values
  9. Aggregation and group by
  10. Concatenate and Merge Dataframe (JOINS)
  11. AI and ChatGPT

In [4]:
# 1. Data Frame
# Creating Pandas
df = pd.DataFrame([11,22,33], columns = ['Col_Name'])
df

   Col_Name
0        11
1        22
2        33

In [5]:
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
#create one dataframe with key values
data = {
    'Name' : ['Rakesh','Blessy','Tarun','Jyothi'],
    'Age' : [16,17,18,19],
    'Salary' : [90000,70000,50000,30000]
    }
data

{'Name': ['Rakesh', 'Blessy', 'Tarun', 'Jyothi'],
 'Age': [16, 17, 18, 19],
 'Salary': [90000, 70000, 50000, 30000]}

In [7]:
print(type(data))

<class 'dict'>

In [8]:
#Convert it to data frame
df = pd.DataFrame(data)
df

     Name  Age  Salary
0  Rakesh   16   90000
1  Blessy   17   70000
2   Tarun   18   50000
3  Jyothi   19   30000

In [9]:
print(type(df))

<class 'pandas.DataFrame'>

In [10]:
# 2. Basic Dataframe Understanding
df.head() # display top 4 rows

     Name  Age  Salary
0  Rakesh   16   90000
1  Blessy   17   70000
2   Tarun   18   50000
3  Jyothi   19   30000

In [11]:
df.head(2) # display only top 2 rows

     Name  Age  Salary
0  Rakesh   16   90000
1  Blessy   17   70000

In [12]:
df.tail() # display only last 4 rows

     Name  Age  Salary
0  Rakesh   16   90000
1  Blessy   17   70000
2   Tarun   18   50000
3  Jyothi   19   30000

In [13]:
df.tail(2) # display last 2 rows

     Name  Age  Salary
2   Tarun   18   50000
3  Jyothi   19   30000

In [14]:
df.shape # check the shape of dataframe (check the number of rows and column)

(4, 3)

In [15]:
df.columns # check the column names

Index(['Name', 'Age', 'Salary'], dtype='str')

In [16]:
df1 = df.rename(columns = {'Salary' : 'Monthly_Salary'}) # changing column name
df1

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [17]:
df

     Name  Age  Salary
0  Rakesh   16   90000
1  Blessy   17   70000
2   Tarun   18   50000
3  Jyothi   19   30000

In [18]:
df.rename(columns = {'Salary' : 'Monthly_Salary'}, inplace = True)
df

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 251.0 bytes

In [20]:
 df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [21]:
# Save and Load Data from csv
# 3a. Save file to csv 
df.to_csv('Test_data1.csv') # goto 'C:\\Users\\JAFFAR\\Home' and check Test_data.csv file

In [22]:
pwd

'C:\\Users\\JAFFAR\\Home'

In [23]:
df

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [24]:
df.to_csv('Test_data2.csv', index = False) # goto 'C:\\Users\\JAFFAR\\Home' and check Test_data.csv file
df

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [25]:
# 3b. Load csv file
load_df = pd.read_csv('Test_data2.csv')
load_df

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [26]:
# 4. Rows & Columns Selection 
# Select only specific column
df[['Name']] # Single Column

     Name
0  Rakesh
1  Blessy
2   Tarun
3  Jyothi

In [27]:
# Select multiple Columns
df[['Name','Monthly_Salary']]

     Name  Monthly_Salary
0  Rakesh           90000
1  Blessy           70000
2   Tarun           50000
3  Jyothi           30000

In [28]:
# Select rows
# methode 1 : select rows based on column names
#loc - index name based (label index)
df.loc[df.Name =='Blessy']

     Name  Age  Monthly_Salary
1  Blessy   17           70000

In [29]:
df.loc[(df.Name == 'Rakesh') & (df.Monthly_Salary >= 50000 )] # loc using condition to filter the rows

     Name  Age  Monthly_Salary
0  Rakesh   16           90000

In [30]:
# Method 2 : select rows based on index values
# iloc - index - value based
df.iloc[0]

Name              Rakesh
Age                   16
Monthly_Salary     90000
Name: 0, dtype: object

In [31]:
df.loc[0:2]

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000

In [32]:
# iloc for  multiple rows using slicing
df.iloc[0:2] # [start:stop:step]

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000

In [33]:
# 5. Filter Data Frame 
df

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [34]:
# Filter the data where age >= 18 
df['Age']>18 # result display in booleam (true or false)

0    False
1    False
2    False
3     True
Name: Age, dtype: bool

In [35]:
df[df['Age']>18] # result should be display in dataframe

     Name  Age  Monthly_Salary
3  Jyothi   19           30000

In [36]:
df[df['Age']>17] # result should be display in dataframe

     Name  Age  Monthly_Salary
2   Tarun   18           50000
3  Jyothi   19           30000

In [37]:
# another method
df_age_filter = df[df['Age']> 17]
df_age_filter

     Name  Age  Monthly_Salary
2   Tarun   18           50000
3  Jyothi   19           30000

In [38]:
# Filter data based on age and Salary
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)]

    Name  Age  Monthly_Salary
2  Tarun   18           50000

In [39]:
# filter data using 'where'
df.where(df['Age'] >= 18)

     Name   Age  Monthly_Salary
0     NaN   NaN             NaN
1     NaN   NaN             NaN
2   Tarun  18.0         50000.0
3  Jyothi  19.0         30000.0

In [40]:
# Put the value 'Not_Eligible' instead of 'NAN'
df.where(df['Age']>=18, other = 'Not_Eligible')

           Name           Age Monthly_Salary
0  Not_Eligible  Not_Eligible   Not_Eligible
1  Not_Eligible  Not_Eligible   Not_Eligible
2         Tarun            18          50000
3        Jyothi            19          30000

In [41]:
# 6. Rows and Columns - Operationsm (Add, Update, Delete)
df

     Name  Age  Monthly_Salary
0  Rakesh   16           90000
1  Blessy   17           70000
2   Tarun   18           50000
3  Jyothi   19           30000

In [42]:
# Add new column
df['Team'] = ['CEO','HR','CTO','DA']
df

     Name  Age  Monthly_Salary Team
0  Rakesh   16           90000  CEO
1  Blessy   17           70000   HR
2   Tarun   18           50000  CTO
3  Jyothi   19           30000   DA

In [43]:
# Add new column by performing multiplication operation
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0

In [44]:
# Adding new rows
df.loc[len(df)] = ['ABC',21,21000,'IT',2000]
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0
4     ABC   21           21000   IT   2000.0

In [45]:
#check length of dataframe
len(df)

5

In [46]:
# Update value using index number
df.loc[0,'Monthly_Salary'] = 95000
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           95000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0
4     ABC   21           21000   IT   2000.0

In [47]:
# Update value using column name
df.loc[df.Name == 'Rakesh', 'Monthly_Salary'] = 90000
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0
4     ABC   21           21000   IT   2000.0

In [48]:
# Delete the value from row , axis = 0
df = df.drop(df[df.Name == 'ABC'].index)
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0

In [49]:
# Drop 'Bonus' Column.. I delete the column are Bonus, Team, Name 
df.drop('Name', axis = 1)

   Age  Monthly_Salary Team    Bonus
0   16           90000  CEO  18000.0
1   17           70000   HR  14000.0
2   18           50000  CTO  10000.0
3   19           30000   DA   6000.0

In [50]:
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0

In [51]:
# Delete multiple column
#df.drop(['Name','Age'])

In [52]:
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0

In [53]:
# Again add new column 'Team'
df['Team'] = ['CEO','HR','CTO','DA']
df

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0

In [54]:
# sort the values in ascending order, by default
df.sort_values('Monthly_Salary')

     Name  Age  Monthly_Salary Team    Bonus
3  Jyothi   19           30000   DA   6000.0
2   Tarun   18           50000  CTO  10000.0
1  Blessy   17           70000   HR  14000.0
0  Rakesh   16           90000  CEO  18000.0

In [55]:
# Sort the values in descending order
df.sort_values('Monthly_Salary', ascending = False)

     Name  Age  Monthly_Salary Team    Bonus
0  Rakesh   16           90000  CEO  18000.0
1  Blessy   17           70000   HR  14000.0
2   Tarun   18           50000  CTO  10000.0
3  Jyothi   19           30000   DA   6000.0

In [56]:
# 7. working with date values
# Creat a new column called 'DOJ'
df['DOJ'] = ['2024-01-01','2024-01-15','2024-03-28','2024-03-03']
df

     Name  Age  Monthly_Salary Team    Bonus         DOJ
0  Rakesh   16           90000  CEO  18000.0  2024-01-01
1  Blessy   17           70000   HR  14000.0  2024-01-15
2   Tarun   18           50000  CTO  10000.0  2024-03-28
3  Jyothi   19           30000   DA   6000.0  2024-03-03

In [57]:
df['DOJ'].dtype

In [58]:
# Update datatype for 'DOJ' column
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [59]:
df['DOJ'].dtype

dtype('<M8[us]')

# means:

##### dtype → data type
##### M8 → datetime64 (date/time)
##### [us] → microseconds
##### < → little-endian byte order

In [60]:
# Again create a new column
df1 = df

In [61]:
df1['DOJ2'] = ['01-01-2025','15-01-2025','28-03-2025','03-03-2025']
df1

     Name  Age  Monthly_Salary Team    Bonus        DOJ        DOJ2
0  Rakesh   16           90000  CEO  18000.0 2024-01-01  01-01-2025
1  Blessy   17           70000   HR  14000.0 2024-01-15  15-01-2025
2   Tarun   18           50000  CTO  10000.0 2024-03-28  28-03-2025
3  Jyothi   19           30000   DA   6000.0 2024-03-03  03-03-2025

In [62]:
df1['DOJ2'].dtype

# Important date-format list

| Format | Meaning          | Example     |
| ------ | ---------------- | ----------- |
| `%d`   | Day (01–31)      | `25`        |
| `%m`   | Month (01–12)    | `09`        |
| `%Y`   | Year, 4 digits   | `2026`      |
| `%y`   | Year, 2 digits   | `26`        |
| `%B`   | Full month name  | `September` |
| `%b`   | Short month name | `Sep`       |
| `%A`   | Full day name    | `Friday`    |
| `%a`   | Short day name   | `Fri`       |

| Format | Meaning      | Example |
| ------ | ------------ | ------- |
| `%H`   | Hour (00–23) | `14`    |
| `%I`   | Hour (01–12) | `02`    |
| `%M`   | Minute       | `30`    |
| `%S`   | Second       | `45`    |
| `%p`   | AM/PM        | `PM`    |

In [63]:
# upadte datatype as dd-mm-yy format
df['DOJ2'] = pd.to_datetime(df['DOJ2'],format = '%d-%m-%Y')

In [64]:
df['DOJ2'].dtype

dtype('<M8[us]')

In [65]:
df

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2
0  Rakesh   16           90000  CEO  18000.0 2024-01-01 2025-01-01
1  Blessy   17           70000   HR  14000.0 2024-01-15 2025-01-15
2   Tarun   18           50000  CTO  10000.0 2024-03-28 2025-03-28
3  Jyothi   19           30000   DA   6000.0 2024-03-03 2025-03-03

In [66]:
# drop the last column
df.drop('DOJ2', axis = 1)

     Name  Age  Monthly_Salary Team    Bonus        DOJ
0  Rakesh   16           90000  CEO  18000.0 2024-01-01
1  Blessy   17           70000   HR  14000.0 2024-01-15
2   Tarun   18           50000  CTO  10000.0 2024-03-28
3  Jyothi   19           30000   DA   6000.0 2024-03-03

In [67]:
# convert 'DOJ' column to datetime datatype
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [68]:
df['DOJ'].dtype

dtype('<M8[us]')

In [69]:
# Display only year, month, week, day
print('Years are :',df['DOJ'].dt.year)
print()
print('Months are :',df['DOJ'].dt.month)
print()
print('Days are :',df['DOJ'].dt.day)
print()
print('Day Names are :',df['DOJ'].dt.day_name())

Years are : 0    2024
1    2024
2    2024
3    2024
Name: DOJ, dtype: int32

Months are : 0    1
1    1
2    3
3    3
Name: DOJ, dtype: int32

Days are : 0     1
1    15
2    28
3     3
Name: DOJ, dtype: int32

Day Names are : 0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [70]:
# create a column for probation period called 'Month' and display the probation period data
df['Month'] = df['DOJ'].dt.month
df

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2  Month
0  Rakesh   16           90000  CEO  18000.0 2024-01-01 2025-01-01      1
1  Blessy   17           70000   HR  14000.0 2024-01-15 2025-01-15      1
2   Tarun   18           50000  CTO  10000.0 2024-03-28 2025-03-28      3
3  Jyothi   19           30000   DA   6000.0 2024-03-03 2025-03-03      3

In [71]:
# In 'DOJ' column add 90 days
df['DOJ'] + pd.Timedelta(days = 90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[us]

In [72]:
# 8. Handling Missing values
df

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2  Month
0  Rakesh   16           90000  CEO  18000.0 2024-01-01 2025-01-01      1
1  Blessy   17           70000   HR  14000.0 2024-01-15 2025-01-15      1
2   Tarun   18           50000  CTO  10000.0 2024-03-28 2025-03-28      3
3  Jyothi   19           30000   DA   6000.0 2024-03-03 2025-03-03      3

In [73]:
# check the null values in data set
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus    DOJ   DOJ2  Month
0  False  False           False  False  False  False  False  False
1  False  False           False  False  False  False  False  False
2  False  False           False  False  False  False  False  False
3  False  False           False  False  False  False  False  False

In [77]:
# Create Null values into the given dataset
import numpy as np
df.loc[df.Name == 'Rakesh','Monthly_Salary'] = np.nan
df

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2  Month
0  Rakesh   16             NaN  CEO  18000.0 2024-01-01 2025-01-01      1
1  Blessy   17         70000.0   HR  14000.0 2024-01-15 2025-01-15      1
2   Tarun   18         50000.0  CTO  10000.0 2024-03-28 2025-03-28      3
3  Jyothi   19         30000.0   DA   6000.0 2024-03-03 2025-03-03      3

In [79]:
# check the null values in data set
df.isnull()

    Name    Age  Monthly_Salary   Team  Bonus    DOJ   DOJ2  Month
0  False  False            True  False  False  False  False  False
1  False  False           False  False  False  False  False  False
2  False  False           False  False  False  False  False  False
3  False  False           False  False  False  False  False  False

In [80]:
# Check the sum of null values
df.isnull().sum()

Name              0
Age               0
Monthly_Salary    1
Team              0
Bonus             0
DOJ               0
DOJ2              0
Month             0
dtype: int64

In [81]:
# Fill the null Values
df.fillna(0)

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2  Month
0  Rakesh   16             0.0  CEO  18000.0 2024-01-01 2025-01-01      1
1  Blessy   17         70000.0   HR  14000.0 2024-01-15 2025-01-15      1
2   Tarun   18         50000.0  CTO  10000.0 2024-03-28 2025-03-28      3
3  Jyothi   19         30000.0   DA   6000.0 2024-03-03 2025-03-03      3

In [84]:
# 9. Aggregation and group by
#count the values in the column called 'Team'
df['Team'].value_counts()

Team
CEO    1
HR     1
CTO    1
DA     1
Name: count, dtype: int64

In [85]:
#count the values in the column called 'Month'
df['Month'].value_counts()

Month
1    2
3    2
Name: count, dtype: int64

In [92]:
# count the values in janaury Month
df[df['Month']==1].value_counts() # it gives frequency(how many times values are repeated)) of values

Name    Age  Monthly_Salary  Team  Bonus    DOJ         DOJ2        Month
Blessy  17   70000.0         HR    14000.0  2024-01-15  2025-01-15  1        1
Name: count, dtype: int64

In [93]:
# group by
df.groupby('Month')['Monthly_Salary'].sum() # aggregation based on groupby

Month
1    70000.0
3    80000.0
Name: Monthly_Salary, dtype: float64

In [94]:
# Display salary and number of employees
df.groupby('Month').agg({'Monthly_Salary' : 'mean', 'Name' : 'count'})

       Monthly_Salary  Name
Month
1             70000.0     2
3             40000.0     2

In [96]:
# 10. Concatinate and Merge Dataframes 
# Concatinate means 'Copy and Past'
# Merge means 'Joins'

In [112]:
# Create two dataframe
df1a = pd.DataFrame({'ID' : [1,2,3],'Name' : ['A','B','C']})
df1a

   ID Name
0   1    A
1   2    B
2   3    C

In [113]:
df1b = pd.DataFrame({'ID' : [1,2,2,4], 'Score' : [88,96,77,79]})
df1b

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [114]:
# concatinate two dataframe
pd.concat([df1a,df1b],axis = 0) # axis = 0 means vertical/row level/ top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [115]:
pd.concat([df1a,df1b],axis = 1) # Horizontal/ Column Level / Side on Side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [117]:
# Merge = JOIN

pd.merge(df1a,df1b, how = 'inner', on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [119]:
pd.merge(df1a,df1b, how = 'inner', left_on = 'ID', right_on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [107]:
# 11. AI and Chatgpt :
# Generate one prompt 
# Prompt is For the given dataframe, write a pandas script to filter employees whose joining date 
# is in the month of January and whose salary is greater then 70,000

In [122]:
# Name	Age	Monthly_Salary	Team	 DOJ
# 0	Rakesh	16	90000	    CEO		2024-01-01
# 1	Blessy	17	70000	    HR		2024-01-15
# 2	Tarun	18	50000	   CTO		2024-03-28
# 3	Jyothi	19	30000	  DA		2024-03-03
# filter salary > 70000 and Janaury employees
df[(df['Month'] == 1) & (df['Monthly_Salary'] >= 70000)] # This is basic filter method

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2  Month
1  Blessy   17         70000.0   HR  14000.0 2024-01-15 2025-01-15      1

In [123]:
# is there any other method to get the same result
df.query('Month == 1 and Monthly_Salary >= 70000') # query Method

     Name  Age  Monthly_Salary Team    Bonus        DOJ       DOJ2  Month
1  Blessy   17         70000.0   HR  14000.0 2024-01-15 2025-01-15      1

In [125]:
# Home work : Create a dataframe to practice pivote table in pandas (using AI prompt)

In [126]:
pwd

'C:\\Users\\JAFFAR\\Home'